// Authentication actions
const USER_AUTHENTICATED = "USER_AUTHENTICATED";

// Admin actions
const ANALYZE_DATA = "ANALYZE_DATA";
const USERS_REQUESTS = "USERS_REQUEST";

// Popup and modal actions
const POPUP_INDICATED = "POPUP_INDICATED";
const MODAL_INDICATED = "MODAL_INDICATED";

// Logs
const ERROR_INDICATED = "ERROR_INDICATED";
const SUCCESS_INDICATED = "SUCCESS_INDICATED";

export {
      USER_AUTHENTICATED,
      ERROR_INDICATED,
      SUCCESS_INDICATED,
      ANALYZE_DATA,
      USERS_REQUESTS,
      POPUP_INDICATED,
      MODAL_INDICATED
}